/*
 * SYS 로그인해서, 사용자 계정 생성
 */

/* 사용자 계정 생성 */
CREATE USER SQLD IDENTIFIED BY "1234";

/* 생성한 사용자 계정의 잠금 해제 */
ALTER USER SQLD ACCOUNT UNLOCK;     

 /* 생성한 사용자 계정에 권한 부여 */
GRANT RESOURCE, DBA, CONNECT TO SQLD;



/*
 * 테이블 스페이스 및 임시 테이블 스페이스 생성
 */
CREATE TABLESPACE SQLD_DATA
DATAFILE '/u01/app/oracle/oradata/XE/SQLD_DATA.dbf' SIZE 4G
AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED
LOGGING
ONLINE 
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE TEMPORARY TABLESPACE SQLD_TEMP
TEMPFILE '/u01/app/oracle/oradata/XE/SQLD_TEMP.dbf' SIZE 1G
AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;



/*
 * 디폴트 및 임시 테이블 스페이스 지정 - SYS 계정에서 실행
 */
ALTER USER SQLD DEFAULT TABLESPACE SQLD_DATA;
ALTER USER SQLD TEMPORARY TABLESPACE SQLD_TEMP;



/**
 * 데이터 덤프를 위한 디렉토리 권한 설정: 실행/쓰기/읽기 권한 부여
 */
CREATE OR REPLACE DIRECTORY D_SQLD AS '/SQLD';
GRANT EXECUTE ON DIRECTORY D_SQLD TO SQLD WITH GRANT OPTION;
GRANT WRITE ON DIRECTORY D_SQLD TO SQLD WITH GRANT OPTION;
GRANT READ ON DIRECTORY D_SQLD TO SQLD WITH GRANT OPTION;


/**
 * 인코딩 MS949로 써야해서 테이블 다시 지우기로 했다. ㅠㅠ
 * 
 */
DROP TABLE SQLD.TB_ADRES_CL PURGE; 
DROP TABLE SQLD.TB_ADRES_CL_SE PURGE;
DROP TABLE SQLD.TB_ADSTRD PURGE; 
DROP TABLE SQLD.TB_AGRDE_SE PURGE; 
DROP TABLE SQLD.TB_BSSH PURGE; 
DROP TABLE SQLD.TB_INDUTY_CL PURGE; 
DROP TABLE SQLD.TB_INDUTY_CL_SE PURGE; 
DROP TABLE SQLD.TB_PLOT_SE PURGE; 
DROP TABLE SQLD.TB_POPLTN PURGE; 
DROP TABLE SQLD.TB_POPLTN_SE PURGE; 
DROP TABLE SQLD.TB_RN PURGE;
DROP TABLE SQLD.TB_STDR_INDUST_CL PURGE; 
DROP TABLE SQLD.TB_SUBWAY_STATN PURGE; 
DROP TABLE SQLD.TB_SUBWAY_STATN_TK_GFF PURGE; 
DROP TABLE SQLD.TB_TK_GFF_SE PURGE; 




